name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: arc-runner-set

    # strategy:
    #   matrix:
    #     go-version: ["1.23.2"]

    steps:
      - name: Update package list
        run: sudo apt-get update

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Install Chromium dependencies
        run: |
          sudo apt-get install -y \
          libgbm1 \
          libxss1 \
          libasound2 \
          libatk1.0-0 \
          libc6 \
          libcairo2 \
          libcups2 \
          libdbus-1-3 \
          libexpat1 \
          libfontconfig1 \
          libgcc1 \
          libgconf-2-4 \
          libgdk-pixbuf2.0-0 \
          libglib2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libstdc++6 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrandr2 \
          libxrender1 \
          libxtst6 \
          ca-certificates \
          fonts-liberation \
          libappindicator1 \
          libnss3 \
          lsb-release \
          xdg-utils \
          wget

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm ci --save-dev

      - name: Run tests
        run: npm run test

      - name: "Build: Unpacked"
        run: |
          npm run build
          mkdir -p artifacts
          zip -r ./artifacts/dist.zip ./dist

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: pt-coupon-unpacked
          path: ./dist.zip

  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: "${{ matrix.go-version }}"

  #     - name: Install dependencies
  #       run: go mod download

  #     - name: Run tests
  #       run: go test ./...

  #     - name: Build
  #       run: go build -o ./bin/main .

  # build:
  #   runs-on: arc-runner-set
  #   needs: test

  #   strategy:
  #     matrix:
  #       go-version: ["1.23.2"]
  #       os:
  #         - linux
  #         - darwin
  #         - windows
  #       arch:
  #         - amd64
  #         - arm64

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: "${{ matrix.go-version }}"

  #     - name: Install dependencies
  #       run: go mod download

  #     - name: Build
  #       run:
  #         GOOS="${{ matrix.os }}" GOARCH="${{ matrix.arch }}" go build -o
  #         ./bin/rainbowtable-${{ matrix.os }}-${{ matrix.arch }} .

  #     - name: Publish artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: rainbowtable-${{ matrix.os }}-${{ matrix.arch }}
  #         path: ./bin/*
