name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: arc-runner-set

    steps:
      - name: Install software
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
            sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libappindicator1 \
            libasound2 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libgcc1 \
            libgconf-2-4 \
            libgdk-pixbuf2.0-0 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            lsb-release \
            wget \
            xdg-utils \
            zip

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm ci --save-dev

      - name: Run tests
        run: npm run test

      - name: "Build: Unpacked"
        run: |
          npm run build
          mkdir -p artifacts
          zip -r ./artifacts/dist.zip ./dist

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: pt-coupon-unpacked
          path: ./dist.zip
