name: ptsemrelease.py

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: arc-runner-set
    concurrency:
      group: semantic-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run ptsemrelease.py
        run: |
          python3 scripts/ptsemrelease.py \
              --version 0.0.0 \
              --prerelease-pattern develop develop \
              --commit \
              --commit-push \
              --tag \
              --tag-create-for-prerelease \
              --tag-force \
              --tag-force-push \
              --tag-push \
              --branch \
              --branch-force \
              --branch-push \
              --branch-create-minor \
              --branch-create-major \
              --string-write ./VERSION \
              --json-write ./public/manifest.json version \
              --json-write ./package.json version
