name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: arc-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm ci --save-dev

      - name: Run tests
        run: npm run test
